import type { LucideIcon } from 'lucide-react';
import {
    Armchair,
    Banknote,
    ChartLine,
    FileText,
    MessageSquareText,
    PanelsTopLeft,
    Truck,
    UtensilsCrossed,
    ShieldCheck,
    Zap,
    Globe,
    Smartphone,
    Laptop,
    Users,
    Rocket,
    TrendingUp,
    Cloud,
    Code,
    Database,
    Lock,
    Search,
    ShoppingCart,
    Star,
    Wrench,
    Heart,
    Camera,
    Headphones,
    MapPin,
    Calendar,
    Bell
} from 'lucide-react';

export const IconRegistry: Record<string, LucideIcon> = {
    Armchair,
    Banknote,
    ChartLine,
    FileText,
    MessageSquareText,
    PanelsTopLeft,
    Truck,
    UtensilsCrossed,
    ShieldCheck,
    Zap,
    Globe,
    Smartphone,
    Laptop,
    Users,
    Rocket,
    TrendingUp,
    Cloud,
    Code,
    Database,
    Lock,
    Search,
    ShoppingCart,
    Star,
    Wrench,
    Heart,
    Camera,
    Headphones,
    MapPin,
    Calendar,
    Bell
};

export const getIconComponent = (name: string): LucideIcon => {
    return IconRegistry[name] || FileText;
};
